import { StyleSheet, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

export const getStyles = (isDarkMode: boolean, isRTL: boolean, isScheduledOffer: boolean) =>
StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: isDarkMode ? '#0f0f0f' : '#ffffff',
  },
  statusBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: isDarkMode ? 'rgba(0,0,0,0.8)' : 'rgba(255,255,255,0.9)',
    borderBottomWidth: 1,
    borderBottomColor: isDarkMode ? '#333' : '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 1000,
  },
  statusText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  shiftTimeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  connectionIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginLeft: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.6,
    shadowRadius: 3,
    elevation: 4,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.3)' : 'rgba(0,0,0,0.2)',
  },
  header: {
    position: 'absolute',
    top: 60,
    left: isRTL ? undefined : 20,
    right: isRTL ? 20 : undefined,
    zIndex: 1000,
  },
  menuButton: {
    width: 52,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: isDarkMode ? 'rgba(15,23,42,0.75)' : 'rgba(255,255,255,0.95)',
    borderRadius: 26,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(148,163,184,0.25)' : 'rgba(15,23,42,0.08)',
  },
  menuButtonActive: {
    backgroundColor: isDarkMode ? 'rgba(56,189,248,0.22)' : '#e0f2fe',
    borderColor: isDarkMode ? 'rgba(56,189,248,0.6)' : '#7dd3fc',
    shadowColor: '#38bdf8',
    shadowOpacity: 0.4,
  },
  pendingBadgeOnMenuButton: {
    position: 'absolute',
    top: -5,
    right: -5,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#fff',
  },
  hamburgerLine: {
    width: 22,
    height: 3,
    backgroundColor: isDarkMode ? '#e2e8f0' : '#0f172a',
    marginVertical: 2,
    borderRadius: 2,
  },
  menuLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1500,
  },
  menuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: isDarkMode ? 'rgba(2,6,23,0.45)' : 'rgba(15,23,42,0.18)',
  },
  menuOverlay: {
    position: 'absolute',
    top: 120,
    left: isRTL ? undefined : 16,
    right: isRTL ? 16 : undefined,
    backgroundColor: isDarkMode ? 'rgba(17,24,39,0.98)' : 'rgba(255,255,255,0.98)',
    borderRadius: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 14,
    minWidth: 230,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(148,163,184,0.18)' : 'rgba(15,23,42,0.08)',
    zIndex: 1000,
    overflow: 'hidden',
    paddingVertical: 6,
  },
  menuItem: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    minHeight: 50,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: isDarkMode ? 'rgba(148,163,184,0.18)' : 'rgba(15,23,42,0.06)',
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.02)' : 'transparent',
  },
  menuItemWarning: {
    backgroundColor: isDarkMode ? 'rgba(255,193,7,0.16)' : '#fff8e1',
  },
  menuItemDanger: {
    backgroundColor: isDarkMode ? 'rgba(220,53,69,0.16)' : '#fff1f2',
  },
  menuItemIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.08)' : '#f1f5f9',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(148,163,184,0.25)' : '#e2e8f0',
  },
  menuItemIcon: {
    fontSize: 16,
  },
  menuItemText: {
    flex: 1,
    fontSize: 15,
    color: isDarkMode ? '#f8fafc' : '#0f172a',
    fontWeight: '600',
    textAlign: isRTL ? 'right' : 'left',
  },
  menuItemArrow: {
    fontSize: 18,
    color: isDarkMode ? 'rgba(226,232,240,0.6)' : '#94a3b8',
    marginLeft: isRTL ? 0 : 4,
    marginRight: isRTL ? 4 : 0,
  },
  pendingBadgeOnMenuItem: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  pendingBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 12,
  },
  mapContainer: {
    position: 'absolute',
    top: 140,
    left: 0,
    right: 0,
    minHeight: 300,
    maxHeight: 440,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    backgroundColor: isDarkMode ? 'rgba(15,23,42,0.96)' : '#f8fafc',
    borderRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(148,163,184,0.12)' : '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 14,
    zIndex: 10,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  mapDisabledContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  mapPlaceholderText: {
    fontSize: 16,
    color: isDarkMode ? '#ccc' : '#666',
    textAlign: 'center',
  },
  mapKeyLabel: {
    marginTop: 12,
    fontSize: 14,
    fontWeight: '600',
    color: isDarkMode ? '#e5e7eb' : '#111827',
  },
  mapKeyText: {
    marginTop: 6,
    fontSize: 13,
    color: isDarkMode ? '#d1d5db' : '#4b5563',
    textAlign: 'center',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000,
  },
  kmInput: {
    height: 50,
    borderColor: isDarkMode ? '#555' : '#ddd',
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 20,
    paddingHorizontal: 15,
    fontSize: 16,
    backgroundColor: isDarkMode ? '#333' : '#f9f9f9',
    color: isDarkMode ? '#fff' : '#000',
    textAlign: 'center',
  },
  personIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'gray',
    justifyContent: 'center',
    alignItems: 'center',
  },
  personHead: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'white',
    position: 'absolute',
    top: 4,
  },
  personBody: {
    width: 4,
    height: 12,
    backgroundColor: 'white',
    position: 'absolute',
    bottom: 4,
  },
  rideModalContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  rideModalCard: {
    backgroundColor: isDarkMode ? 'rgba(40,40,40,0.95)' : 'rgba(255,255,255,0.95)',
    margin: 20,
    borderRadius: 20,
    padding: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 15,
    alignItems: 'stretch',
    position: 'relative',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)',
  },
  pickupModalCard: {
    backgroundColor: isDarkMode ? 'rgba(30,30,30,0.97)' : 'rgba(255,255,255,0.98)',
    margin: 20,
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 18,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.08)',
    borderTopWidth: 4,
    borderTopColor: '#28a745',
  },
  pickupHandle: {
    alignSelf: 'center',
    width: 50,
    height: 5,
    borderRadius: 999,
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.2)' : '#e2e8f0',
    marginBottom: 12,
  },
  pickupHeaderRow: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  pickupBadge: {
    backgroundColor: isDarkMode ? 'rgba(34,197,94,0.18)' : '#dcfce7',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(34,197,94,0.45)' : '#bbf7d0',
  },
  pickupBadgeText: {
    color: isDarkMode ? '#86efac' : '#15803d',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  pickupHeaderMeta: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'center',
    gap: 8,
  },
  pickupIdPill: {
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.08)' : '#f1f3f5',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.15)' : '#e2e8f0',
  },
  pickupIdText: {
    fontSize: 12,
    fontWeight: '700',
    color: isDarkMode ? '#e2e8f0' : '#334155',
  },
  pickupInfoRow: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    gap: 10,
    marginBottom: 14,
  },
  pickupInfoCard: {
    flex: 1,
    backgroundColor: isDarkMode ? '#252525' : '#f8f9fa',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)',
  },
  pickupInfoLabel: {
    fontSize: 12,
    color: isDarkMode ? '#aaa' : '#6b7280',
    marginBottom: 4,
    textAlign: isRTL ? 'right' : 'left',
  },
  pickupInfoValue: {
    fontSize: 16,
    fontWeight: '700',
    color: isDarkMode ? '#fff' : '#111827',
    textAlign: isRTL ? 'right' : 'left',
  },
  pickupInfoValueAccent: {
    color: '#22c55e',
  },
  pickupAddressCard: {
    backgroundColor: isDarkMode ? '#1f2d1f' : '#f0fdf4',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(34,197,94,0.25)' : '#bbf7d0',
    marginBottom: 14,
  },
  pickupAddressHeader: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  pickupAddressLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: isDarkMode ? '#86efac' : '#15803d',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  pickupAddressValue: {
    fontSize: 16,
    color: isDarkMode ? '#e2e8f0' : '#1f2937',
    fontWeight: '600',
    lineHeight: 22,
    textAlign: isRTL ? 'right' : 'left',
  },
  stopAddressCard: {
    backgroundColor: isDarkMode ? '#2b2115' : '#fffbeb',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(245,158,11,0.35)' : '#fcd34d',
    marginBottom: 14,
  },
  stopAddressHeader: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  stopDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#f59e0b',
    marginRight: isRTL ? 0 : 8,
    marginLeft: isRTL ? 8 : 0,
  },
  stopAddressLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: isDarkMode ? '#fbbf24' : '#b45309',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  stopAddressValue: {
    fontSize: 16,
    color: isDarkMode ? '#fde68a' : '#7c2d12',
    fontWeight: '600',
    lineHeight: 22,
    textAlign: isRTL ? 'right' : 'left',
  },
  pickupActions: {
    gap: 10,
  },
  pickupActionRow: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    gap: 10,
  },
  pickupActionButton: {
    flex: 1,
  },
  pickupNavButton: {
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.08)' : '#f1f5f9',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.2)' : '#e2e8f0',
  },
  pickupNavText: {
    color: isDarkMode ? '#e2e8f0' : '#0f172a',
    fontSize: 15,
    fontWeight: '700',
  },
  pickupChatButton: {
    backgroundColor: isDarkMode ? 'rgba(56,189,248,0.18)' : '#e0f2fe',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(56,189,248,0.45)' : '#bae6fd',
  },
  pickupChatButtonText: {
    color: isDarkMode ? '#bae6fd' : '#0369a1',
    fontSize: 15,
    fontWeight: '700',
  },
  dropoffModalCard: {
    backgroundColor: isDarkMode ? 'rgba(30,30,30,0.97)' : 'rgba(255,255,255,0.98)',
    margin: 20,
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 18,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.08)',
    borderTopWidth: 4,
    borderTopColor: '#dc3545',
  },
  dropoffHandle: {
    alignSelf: 'center',
    width: 50,
    height: 5,
    borderRadius: 999,
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.2)' : '#e2e8f0',
    marginBottom: 12,
  },
  dropoffHeaderRow: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  dropoffBadge: {
    backgroundColor: isDarkMode ? 'rgba(220,53,69,0.18)' : '#fee2e2',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(220,53,69,0.4)' : '#fecaca',
  },
  dropoffBadgeText: {
    color: isDarkMode ? '#fecaca' : '#b91c1c',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  dropoffIdPill: {
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.08)' : '#f1f3f5',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.15)' : '#e2e8f0',
  },
  dropoffIdText: {
    fontSize: 12,
    fontWeight: '700',
    color: isDarkMode ? '#e2e8f0' : '#334155',
  },
  dropoffInfoRow: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    gap: 10,
    marginBottom: 14,
  },
  dropoffInfoCard: {
    flex: 1,
    backgroundColor: isDarkMode ? '#252525' : '#f8f9fa',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)',
  },
  dropoffInfoLabel: {
    fontSize: 12,
    color: isDarkMode ? '#aaa' : '#6b7280',
    marginBottom: 4,
    textAlign: isRTL ? 'right' : 'left',
  },
  dropoffInfoValue: {
    fontSize: 16,
    fontWeight: '700',
    color: isDarkMode ? '#fff' : '#111827',
    textAlign: isRTL ? 'right' : 'left',
  },
  dropoffInfoValueAccent: {
    color: '#22c55e',
  },
  dropoffAddressCard: {
    backgroundColor: isDarkMode ? '#1f2937' : '#f8fafc',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.08)' : '#e2e8f0',
    marginBottom: 14,
  },
  dropoffAddressHeader: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  dropoffDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#dc3545',
    marginRight: isRTL ? 0 : 8,
    marginLeft: isRTL ? 8 : 0,
  },
  dropoffAddressLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: isDarkMode ? '#fecaca' : '#b91c1c',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  dropoffAddressValue: {
    fontSize: 16,
    color: isDarkMode ? '#e2e8f0' : '#1f2937',
    fontWeight: '600',
    lineHeight: 22,
    textAlign: isRTL ? 'right' : 'left',
  },
  dropoffActions: {
    gap: 10,
  },
  dropoffNavButton: {
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.08)' : '#f1f5f9',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.2)' : '#e2e8f0',
  },
  dropoffNavText: {
    color: isDarkMode ? '#e2e8f0' : '#0f172a',
    fontSize: 15,
    fontWeight: '700',
  },
  rideModalHeaderRow: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  rideIdPill: {
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.08)' : '#f1f3f5',
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.15)' : '#e2e8f0',
  },
  rideIdPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: isDarkMode ? '#e2e8f0' : '#334155',
  },
  rideMetaRow: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  rideMetaPill: {
    backgroundColor: isDarkMode ? 'rgba(34,197,94,0.12)' : '#dcfce7',
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(34,197,94,0.3)' : '#bbf7d0',
  },
  rideMetaPillText: {
    color: isDarkMode ? '#86efac' : '#15803d',
    fontSize: 12,
    fontWeight: '700',
  },
  ridePickupLabelRow: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  pickupDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#28a745',
    marginRight: isRTL ? 0 : 8,
    marginLeft: isRTL ? 8 : 0,
  },
  ridePickupLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: isDarkMode ? '#9ae6b4' : '#15803d',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  rideModalPrice: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#28a745',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    textAlign: isRTL ? 'right' : 'left',
  },
  rideModalDistance: {
    fontSize: 16,
    color: isDarkMode ? '#ccc' : '#666',
    marginBottom: 4,
    textAlign: isRTL ? 'right' : 'left',
  },
  rideModalAddress: {
    fontSize: 16,
    color: isDarkMode ? '#e2e8f0' : '#1f2937',
    marginBottom: 6,
    lineHeight: 22,
    fontWeight: '600',
    textAlign: isRTL ? 'right' : 'left',
  },
  rideModalType: {
    fontSize: 16,
    color: isDarkMode ? '#ccc' : '#666',
    marginBottom: 8,
  },
  rideTypeBadge: {
    alignSelf: isRTL ? 'flex-end' : 'flex-start',
    backgroundColor: isDarkMode ? 'rgba(59,130,246,0.15)' : '#e0f2fe',
    borderColor: isDarkMode ? 'rgba(59,130,246,0.3)' : '#bae6fd',
    borderWidth: 1,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    marginBottom: 12,
  },
  rideTypeBadgeText: {
    color: isDarkMode ? '#93c5fd' : '#0369a1',
    fontSize: 12,
    fontWeight: '700',
  },
  rideModalId: {
    position: 'absolute',
    top: 10,
    left: 10,
    fontSize: 14,
    color: isDarkMode ? '#ccc' : '#999',
    fontWeight: 'bold',
  },
  rideModalButtons: {
    flexDirection: 'column',
    width: '100%',
    gap: 10,
    alignItems: 'stretch',
  },
  rideActionRow: {
    flexDirection: isRTL ? 'row-reverse' : 'row',
    gap: 10,
  },
  rideActionButton: {
    flex: 1,
    width: 'auto',
  },
  rideNavButton: {
    backgroundColor: '#007bff',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  rideNavButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  pickupButton: {
    backgroundColor: '#28a745',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#28a745',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.2)' : '#fff',
  },
  pickupButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  dropoffButton: {
    backgroundColor: '#dc3545',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#dc3545',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.2)' : '#fff',
  },
  dropoffButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  sliderContainer: {
    width: '100%',
    justifyContent: 'center',
  },
  sliderTrack: {
    height: 50,
    backgroundColor: isDarkMode ? '#555' : '#f0f0f0',
    borderRadius: 25,
    position: 'relative',
    overflow: 'hidden',
  },
  sliderFill: {
    height: '100%',
    backgroundColor: '#28a745',
    borderRadius: 25,
  },
  sliderThumb: {
    position: 'absolute',
    top: 0,
    width: 50,
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  sliderThumbText: {
    color: '#28a745',
    fontSize: 20,
    fontWeight: 'bold',
  },
  sliderText: {
    textAlign: 'center',
    marginTop: 8,
    fontSize: 14,
    color: isDarkMode ? '#ccc' : '#666',
  },
  sliderSpinner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  spinner: {
    width: 30,
    height: 30,
    borderWidth: 3,
    borderColor: '#28a745',
    borderTopColor: 'transparent',
    borderRadius: 15,
  },
  endShiftMenu: {
    backgroundColor: isDarkMode ? '#333' : '#fff',
    margin: 20,
    borderRadius: 10,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  endShiftTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: isDarkMode ? '#fff' : '#333',
    textAlign: 'center',
    marginBottom: 10,
  },
  endShiftMessage: {
    fontSize: 16,
    color: isDarkMode ? '#ccc' : '#666',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 22,
  },
  endShiftButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  endShiftButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#6c757d',
  },
  confirmButton: {
    backgroundColor: '#dc3545',
  },
  cancelButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  cancelOnText: {
    color: '#dc3545',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 10,
  },
  confirmButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  floatingGoButton: {
    position: 'absolute',
    bottom: 40,
    left: '50%',
    marginLeft: -45, // Half of width to center
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#28a745',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 20,
    borderWidth: 4,
    borderColor: '#fff',
  },
  floatingGoButtonText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
   rideOfferModal: {
     position: 'absolute',
     top: 0,
     left: 0,
     right: 0,
     bottom: 0,
     backgroundColor: 'rgba(0, 0, 0, 0.55)',
     justifyContent: 'flex-end',
     alignItems: 'center',
     zIndex: 3000,
   },
   rideOfferSheet: {
     backgroundColor: isDarkMode ? '#1f1f1f' : '#ffffff',
     width: '100%',
     borderTopLeftRadius: 24,
     borderTopRightRadius: 24,
     padding: 20,
     paddingBottom: 28,
     shadowColor: '#000',
     shadowOffset: { width: 0, height: -6 },
     shadowOpacity: 0.2,
     shadowRadius: 12,
     elevation: 20,
     borderWidth: 1,
     borderColor: isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.08)',
   },
   rideOfferHeader: {
     flexDirection: 'row',
     justifyContent: 'space-between',
     alignItems: 'center',
     marginBottom: 12,
   },
   rideOfferTitle: {
     fontSize: 18,
     fontWeight: '700',
     color: isDarkMode ? '#fff' : '#222',
     flex: 1,
   },
   scheduledOfferTitle: {
     fontSize: 22,
     fontWeight: '800',
     color: isDarkMode ? '#fff' : '#111827',
   },
   rideOfferPill: {
     backgroundColor: isDarkMode ? '#2f2f2f' : '#f1f3f5',
     borderRadius: 20,
     paddingVertical: 6,
     paddingHorizontal: 12,
     marginLeft: 12,
   },
   rideOfferPillText: {
     color: isDarkMode ? '#fff' : '#333',
     fontSize: 12,
     fontWeight: '600',
   },
   rideOfferMetaRow: {
     flexDirection: 'row',
     justifyContent: 'space-between',
      gap: 10,
      marginBottom: 14,
    },
    rideOfferEtaBanner: {
      width: '100%',
      backgroundColor: '#007AFF',
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginBottom: 14,
    },
    rideOfferEtaBannerText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
      textAlign: 'center',
    },
    rideOfferMetaItem: {
     flex: 1,
     backgroundColor: isDarkMode ? '#2a2a2a' : '#f8f9fa',
     borderRadius: 12,
     paddingVertical: 10,
     paddingHorizontal: 12,
     borderWidth: 1,
     borderColor: isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)',
   },
   rideOfferMetaLabel: {
     fontSize: 12,
     color: isDarkMode ? '#bbb' : '#666',
     marginBottom: 4,
   },
    rideOfferMetaValue: {
      fontSize: 16,
      fontWeight: '700',
      color: isDarkMode ? '#fff' : '#222',
    },
    rideOfferMetaValueHighlight: {
      fontSize: 16,
      fontWeight: '700',
      color: '#007AFF',
    },
    rideOfferAddressBlock: {
     backgroundColor: isDarkMode ? '#2a2a2a' : '#f8f9fa',
     borderRadius: 14,
     padding: 14,
     marginBottom: 16,
     borderWidth: 1,
     borderColor: isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)',
   },
   scheduledOfferTimeRow: {
     backgroundColor: isDarkMode ? '#2a2a2a' : '#f8f9fa',
     borderRadius: 14,
     padding: 12,
     marginBottom: 14,
     borderWidth: 1,
     borderColor: isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)',
   },
   scheduledOfferTimeLabel: {
     fontSize: 12,
     fontWeight: '700',
     color: isDarkMode ? '#a3a3a3' : '#6b7280',
     marginBottom: 4,
     textAlign: isRTL ? 'right' : 'left',
   },
   scheduledOfferTimeValue: {
     fontSize: 16,
     fontWeight: '700',
     color: isDarkMode ? '#fff' : '#111827',
     textAlign: isRTL ? 'right' : 'left',
   },
   rideOfferAddressRow: {
     flexDirection: isRTL ? 'row-reverse' : 'row',
     alignItems: 'flex-start',
     marginBottom: 10,
   },
   rideOfferAddressLabel: {
     fontSize: 12,
     fontWeight: '700',
     color: isDarkMode ? '#9ad0ff' : '#007bff',
     width: 50,
     textAlign: isRTL ? 'right' : 'left',
   },
   rideOfferAddressValue: {
     flex: 1,
     fontSize: 14,
     color: isDarkMode ? '#e5e5e5' : '#333',
     lineHeight: 20,
     textAlign: isRTL ? 'right' : 'left',
   },
   rideOfferCountdownRow: {
     marginBottom: 16,
   },
   rideOfferCountdownTrack: {
     height: 8,
     backgroundColor: isDarkMode ? '#3a3a3a' : '#e9ecef',
     borderRadius: 8,
     overflow: 'hidden',
   },
    rideOfferCountdownFill: {
      height: '100%',
      backgroundColor: isScheduledOffer ? '#f59e0b' : '#dc3545',
    },
   rideOfferCountdownText: {
     marginTop: 8,
     fontSize: 13,
     fontWeight: '600',
     color: isDarkMode ? '#ffb3b3' : '#b02a37',
     textAlign: 'center',
   },
   rideOfferButtons: {
     flexDirection: 'column',
     gap: 10,
     width: '100%',
   },
   rideOfferButton: {
     paddingVertical: 14,
     paddingHorizontal: 20,
     borderRadius: 12,
     alignItems: 'center',
   },
   rideOfferPrimary: {
     width: '100%',
   },
   rideOfferSecondary: {
     backgroundColor: isDarkMode ? 'rgba(255,255,255,0.08)' : '#f1f3f5',
     borderWidth: 1,
     borderColor: isDarkMode ? 'rgba(255,255,255,0.15)' : '#dee2e6',
     width: '100%',
   },
   rideOfferSecondaryText: {
     color: isDarkMode ? '#f8f9fa' : '#343a40',
     textShadowColor: 'transparent',
   },
   acceptButton: {
     backgroundColor: '#28a745',
     shadowColor: '#28a745',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 2,
    borderColor: '#fff',
  },
   rejectButton: {
     backgroundColor: '#dc3545',
     shadowColor: '#dc3545',
     shadowOffset: { width: 0, height: 4 },
     shadowOpacity: 0.3,
     shadowRadius: 8,
     elevation: 4,
     borderWidth: 2,
     borderColor: '#fff',
   },
  acceptButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  rejectButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  callIconInModal: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.08)' : '#f8fafc',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.15)' : '#e2e8f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  callIconText: {
    color: '#28a745',
    fontSize: 18,
  },
  chatButton: {
    backgroundColor: '#17a2b8',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  chatButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  chatModal: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3000,
  },
  chatModalCard: {
    backgroundColor: isDarkMode ? '#333' : 'white',
    width: '90%',
    maxWidth: 400,
    height: '70%',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    flexDirection: 'column',
  },
  chatModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: isDarkMode ? '#555' : '#f0f0f0',
  },
  chatModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: isDarkMode ? '#fff' : '#333',
  },
  chatModalClose: {
    fontSize: 24,
    color: isDarkMode ? '#ccc' : '#666',
    padding: 5,
  },
  chatMessages: {
    flex: 1,
    paddingVertical: 10,
  },
  chatMessage: {
    marginBottom: 10,
    padding: 10,
    borderRadius: 8,
    maxWidth: '80%',
  },
  driverMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#007bff',
  },
  passengerMessage: {
    alignSelf: 'flex-start',
    backgroundColor: isDarkMode ? '#555' : '#e9ecef',
  },
  messageText: {
    color: '#000',
    fontSize: 14,
  },
  chatInputContainer: {
    flexDirection: 'row',
    paddingTop: 10,
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: isDarkMode ? '#555' : '#ddd',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 10,
    fontSize: 14,
    backgroundColor: isDarkMode ? '#444' : '#f9f9f9',
    color: isDarkMode ? '#fff' : '#000',
  },
  chatSendButton: {
    backgroundColor: '#007bff',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatSendButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  unreadBadge: {
    backgroundColor: '#dc3545',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    paddingHorizontal: 4,
  },
  unreadBadgeText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  quickRepliesContainer: {
    maxHeight: 50,
    paddingVertical: 5,
    borderTopWidth: 1,
    borderTopColor: isDarkMode ? '#555' : '#f0f0f0',
  },
  quickReplyButton: {
    backgroundColor: '#6c757d',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    marginHorizontal: 5,
    marginVertical: 5,
  },
  quickReplyText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  shiftWarningModal: {
    backgroundColor: isDarkMode ? '#333' : '#fff',
    margin: 20,
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    alignItems: 'center',
  },
  shiftWarningTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#dc3545',
    marginBottom: 15,
    textAlign: 'center',
  },
  shiftWarningMessage: {
    fontSize: 16,
    color: isDarkMode ? '#ccc' : '#666',
    textAlign: 'center',
    marginBottom: 10,
    lineHeight: 22,
  },
  shiftWarningButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 20,
  },
  shiftWarningButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    minWidth: 120,
    alignItems: 'center',
  },
  shiftEndShiftButton: {
    backgroundColor: '#dc3545',
  },
  laterButton: {
    backgroundColor: '#6c757d',
  },
  endShiftButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  laterButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  searchingBar: {
    position: 'absolute',
    bottom: 20,
    left: 14,
    right: 14,
    backgroundColor: isDarkMode ? 'rgba(2,6,23,0.92)' : 'rgba(255,255,255,0.98)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    zIndex: 1000,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(34,211,238,0.25)' : 'rgba(14,116,144,0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 16,
    elevation: 14,
  },
  searchingText: {
    textAlign: 'center',
  },
  searchingLetter: {
    color: isDarkMode ? '#f8fafc' : '#0f172a',
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
  },
  searchingSubText: {
    marginTop: 4,
    fontSize: 12,
    color: isDarkMode ? '#94a3b8' : '#475569',
    textAlign: 'center',
    fontWeight: '600',
  },
  searchingProgressRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 11,
  },
  searchingProgressDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginHorizontal: 4,
    backgroundColor: isDarkMode ? '#67e8f9' : '#0284c7',
  },
  scheduleHintBar: {
    position: 'absolute',
    bottom: 138,
    left: 20,
    right: 20,
    backgroundColor: isDarkMode ? 'rgba(220,53,69,0.2)' : '#fff1f2',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(254,202,202,0.4)' : '#fecdd3',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    zIndex: 1001,
  },
  scheduleHintText: {
    color: isDarkMode ? '#fecaca' : '#9f1239',
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '700',
  },
  smartAlertsContainer: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 238,
    zIndex: 1002,
  },
  smartAlertsTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: isDarkMode ? '#e2e8f0' : '#0f172a',
    marginBottom: 6,
  },
  smartAlertCard: {
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 6,
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 5,
  },
  smartAlertIcon: {
    fontSize: 16,
    marginRight: isRTL ? 0 : 8,
    marginLeft: isRTL ? 8 : 0,
    marginTop: 1,
  },
  smartAlertTextWrap: {
    flex: 1,
  },
  smartAlertHeading: {
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 2,
    textAlign: isRTL ? 'right' : 'left',
  },
  smartAlertBody: {
    fontSize: 11,
    color: isDarkMode ? '#e2e8f0' : '#334155',
    lineHeight: 15,
    textAlign: isRTL ? 'right' : 'left',
  },
  cancelRideButton: {
    backgroundColor: '#dc3545',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  cancelRideButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  scheduledInfoBar: {
    position: 'absolute',
    top: 40,
    left: 0,
    right: 0,
    height: 20,
    backgroundColor: isDarkMode ? 'rgba(15,23,42,0.92)' : 'rgba(255,255,255,0.95)',
    borderBottomWidth: 1,
    borderBottomColor: isDarkMode ? 'rgba(148,163,184,0.25)' : '#e2e8f0',
    flexDirection: isRTL ? 'row-reverse' : 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    zIndex: 900,
    gap: 8,
  },
  scheduledInfoColumn: {
    flex: 1,
  },
  scheduledInfoText: {
    fontSize: 11,
    fontWeight: '600',
    color: isDarkMode ? '#e2e8f0' : '#0f172a',
  },
  scheduledInfoTextLeft: {
    textAlign: isRTL ? 'right' : 'left',
  },
  scheduledInfoTextRight: {
    textAlign: isRTL ? 'left' : 'right',
  },
  scheduledBannerContainer: {
    position: 'absolute',
    top: 46,
    left: 16,
    right: 16,
    zIndex: 1200,
  },
  scheduledBannerContainerWithInfoBar: {
    top: 66,
  },
  scheduledBannerCard: {
    backgroundColor: isDarkMode ? 'rgba(17,24,39,0.95)' : '#ffffff',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.12)' : '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 12,
  },
  scheduledBannerTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: isDarkMode ? '#f8fafc' : '#0f172a',
    textAlign: 'center',
  },
  scheduledBannerMessage: {
    fontSize: 14,
    fontWeight: '700',
    color: isDarkMode ? '#e2e8f0' : '#111827',
    marginTop: 4,
    textAlign: 'center',
  },
  scheduledBannerTime: {
    fontSize: 12,
    color: isDarkMode ? '#cbd5f5' : '#475569',
    marginTop: 2,
    textAlign: 'center',
  },
  // Cancel Modal - New Styles
  cancelModalCard: {
    backgroundColor: isDarkMode ? '#1e1e1e' : '#fff',
    margin: 20,
    borderRadius: 20,
    padding: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
    width: '90%',
    maxWidth: 400,
    maxHeight: '80%',
    overflow: 'hidden',
  },
  cancelModalScroll: {
    width: '100%',
    maxHeight: height * 0.62,
  },
  cancelModalScrollContent: {
    paddingBottom: 20,
  },
  cancelModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: isDarkMode ? '#333' : '#f0f0f0',
    backgroundColor: isDarkMode ? '#252525' : '#f8f9fa',
  },
  cancelModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: isDarkMode ? '#fff' : '#333',
    flex: 1,
  },
  cancelModalCloseButton: {
    padding: 5,
  },
  cancelModalCloseText: {
    fontSize: 20,
    color: isDarkMode ? '#999' : '#666',
  },
  cancelStepContainer: {
    padding: 20,
  },
  cancelModalSubtitle: {
    fontSize: 14,
    color: isDarkMode ? '#aaa' : '#666',
    marginBottom: 15,
    textAlign: 'center',
  },
  // Warning Banner
  cancelWarningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? '#3d2817' : '#fff3cd',
    padding: 12,
    borderRadius: 12,
    marginBottom: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#ffc107',
  },
  cancelWarningIcon: {
    fontSize: 20,
    marginRight: 10,
  },
  cancelWarningText: {
    flex: 1,
    fontSize: 12,
    color: isDarkMode ? '#ffc107' : '#856404',
    lineHeight: 18,
  },
  // Fee Preview
  cancelFeePreview: {
    backgroundColor: isDarkMode ? '#252525' : '#f8f9fa',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
  },
  cancelFeeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  cancelFeeLabel: {
    fontSize: 14,
    color: isDarkMode ? '#aaa' : '#666',
  },
  cancelFeeValue: {
    fontSize: 14,
    color: isDarkMode ? '#fff' : '#333',
    fontWeight: '500',
  },
  cancelFeeTotal: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: isDarkMode ? '#444' : '#ddd',
  },
  cancelFeeTotalLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: isDarkMode ? '#fff' : '#333',
  },
  cancelFeeTotalValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#dc3545',
  },
  // Reason Options
  cancelReasonsList: {
    gap: 10,
  },
  cancelReasonOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? '#252525' : '#f8f9fa',
    padding: 15,
    borderRadius: 12,
    borderLeftWidth: 4,
  },
  cancelReasonIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  cancelReasonOptionText: {
    flex: 1,
    fontSize: 15,
    color: isDarkMode ? '#fff' : '#333',
  },
  cancelReasonArrow: {
    fontSize: 20,
    color: isDarkMode ? '#666' : '#999',
  },
  // Confirm Step
  cancelConfirmIconContainer: {
    alignItems: 'center',
    marginBottom: 15,
  },
  cancelConfirmIcon: {
    fontSize: 50,
  },
  cancelConfirmMessage: {
    fontSize: 15,
    color: isDarkMode ? '#ccc' : '#666',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 22,
  },
  cancelSelectedReason: {
    backgroundColor: isDarkMode ? '#252525' : '#f8f9fa',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
  },
  cancelSelectedReasonLabel: {
    fontSize: 12,
    color: isDarkMode ? '#999' : '#666',
    marginBottom: 5,
  },
  cancelSelectedReasonValue: {
    fontSize: 16,
    fontWeight: '500',
    color: isDarkMode ? '#fff' : '#333',
  },
  cancelFinalFee: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: isDarkMode ? '#3d1f1f' : '#f8d7da',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
  },
  cancelFinalFeeLabel: {
    fontSize: 14,
    color: isDarkMode ? '#ff6b6b' : '#721c24',
  },
  cancelFinalFeeValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#dc3545',
  },
  cancelConfirmButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  cancelGoBackButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: isDarkMode ? '#444' : '#e9ecef',
  },
  cancelGoBackButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: isDarkMode ? '#fff' : '#495057',
  },
  cancelConfirmButton: {
    flex: 1.5,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#dc3545',
  },
  cancelConfirmButtonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#fff',
  },
  // Loading Step
  cancelLoadingContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  cancelLoadingText: {
    marginTop: 15,
    fontSize: 14,
    color: isDarkMode ? '#aaa' : '#666',
  },
  // Success Step
  cancelSuccessContainer: {
    alignItems: 'center',
    paddingVertical: 30,
  },
  cancelSuccessIcon: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#28a745',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  cancelSuccessIconText: {
    fontSize: 35,
    color: '#fff',
    fontWeight: 'bold',
  },
  cancelSuccessTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: isDarkMode ? '#fff' : '#333',
    marginBottom: 10,
  },
  cancelSuccessMessage: {
    fontSize: 14,
    color: isDarkMode ? '#aaa' : '#666',
    textAlign: 'center',
  },
  // Error Step
  cancelErrorContainer: {
    alignItems: 'center',
    paddingVertical: 30,
  },
  cancelErrorIcon: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#dc3545',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  cancelErrorIconText: {
    fontSize: 35,
    color: '#fff',
    fontWeight: 'bold',
  },
  cancelErrorTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: isDarkMode ? '#fff' : '#333',
    marginBottom: 10,
  },
  cancelErrorMessage: {
    fontSize: 14,
    color: isDarkMode ? '#aaa' : '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
  cancelRetryButton: {
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 12,
    backgroundColor: '#007bff',
  },
  cancelRetryButtonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#fff',
  },
  // Legacy styles (keep for compatibility)
  cancelReasonButton: {
    backgroundColor: '#6c757d',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
    marginBottom: 10,
  },
  cancelReasonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  closeButton: {
    backgroundColor: '#6c757d',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
